### ISSUE TITLE
JVM fatal error

### ISSUE THREAD

**Issue by sherpal** [botkop/numsca#9]
Hello,
(thanks for the library)
I tried the following very simple code:
```scala
import botkop.{numsca => ns}
import ns.Tensor

object Main {

  def main(args: Array[String]): Unit = {
    val tensor = Tensor(0.2, 0.3, 0.5)
    println(ns.sum(tensor))
  }

}
```

but I ran into this error:
```
[info] running com.b12.Main 
13:41:22.808 [run-main-0] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [CpuBackend] backend
13:41:22.856 [run-main-0] DEBUG org.reflections.Reflections - going to scan these urls:
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/94378c76/f8e7f6ae/joda-time-2.2.jar
file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext/cldrdata.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/c9a2f8b5/84897eab/openblas-0.2.19-1.3-android-x86.jar
file:/Users/adoeraene/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.1/scala-reflect-2.13.1.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/47f52bcd/3a66980a/commons-io-2.4.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/5ef4677f/7f302db4/neoitertools-1.0.0.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/807f55d2/b9b19c83/nd4j-native-0.9.1.jar
file:/usr/local/Cellar/sbt/1.2.6/libexec/bin/sbt-launch.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/02c9dd51/2da8bf55/jackson-0.9.1.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/515895aa/99a1fbd1/lombok-1.16.16.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/17965702/1427a508/stax2-api-3.1.4.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/fdf08fdd/43cca92a/openblas-0.2.19-1.3-macosx-x86_64.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/2d408143/17e26b05/nd4j-native-platform-0.9.1.jar
file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext/dnsns.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/3ef6a231/97705cb7/logback-classic-1.2.3.jar
file:/Users/adoeraene/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.1/scala-library-2.13.1.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/b0e924d1/242192a4/nd4j-buffer-0.9.1.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/d13e1500/33c58251/commons-lang3-3.3.1.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/12ae9651/0db09a3c/openblas-platform-0.2.19-1.3.jar
file:/Users/adoeraene/.sbt/boot/scala-2.12.10/org.scala-sbt/sbt/1.3.7/test-interface-1.0.jar
file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/899c2f32/4598152b/guava-18.0.jar
file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext/sunec.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/891f6cd0/ff1b5461/junit-4.8.2.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/7f74ea0b/aaa73d59/nd4j-context-0.9.1.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/a8e1aeaa/8d05bad2/logback-core-1.2.3.jar
file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext/zipfs.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/e93d229c/ef63af0c/annotations-2.0.1.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/ebffd990/98aec13c/openblas-0.2.19-1.3-linux-x86.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/77e7b33f/f30e9ad9/openblas-0.2.19-1.3-linux-ppc64le.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/768e2354/f377c1be/slf4j-api-1.7.26.jar
file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext/localedata.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/96dd7d8a/f9e2082b/nd4j-native-api-0.9.1.jar
file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext/nashorn.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/793100b1/51e84830/javassist-3.18.2-GA.jar
file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext/jaccess.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/c7176496/01ca712f/openblas-0.2.19-1.3-windows-x86_64.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/5fe7e787/b80b29a4/nd4j-common-0.9.1.jar
file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar
file:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/ext/jfxrt.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/ea7fc2c7/3d1b942d/numsca_2.13-0.1.7.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/959848ff/f8801207/javacpp-1.3.3.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/16c2b02b/b20a1249/openblas-0.2.19-1.3-linux-x86_64.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/e4f179bd/65c5c050/reflections-0.9.10.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/cfea4fe2/0d049e93/nd4j-native-0.9.1-macosx-x86_64.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/14b89ea7/ca304db2/findbugs-annotations-1.3.9-1.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/aa256b44/50401670/openblas-0.2.19-1.3.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/0fd3abec/d7c73f67/openblas-0.2.19-1.3-windows-x86.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/4234f625/ea14e73b/scala-logging_2.13-3.9.2.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/38305271/139c3a45/commons-math3-3.4.1.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/f8a0dc44/d69008cc/openblas-0.2.19-1.3-android-arm.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/0e3d712a/01d10541/snakeyaml-1.12.jar
file:/System/Library/Java/Extensions/MRJToolkit.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/job-1/target/db64135f/319a1b12/densitygenerator_2.13-0.2.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/a9165e8b/c54e8441/openblas-0.2.19-1.3-linux-armhf.jar
file:/var/folders/lz/ntshj56x7dn9c855r67vpslh0000gq/T/sbt_3071a00/target/3649a620/f745e5e0/nd4j-api-0.9.1.jar
13:41:22.965 [run-main-0] INFO org.reflections.Reflections - Reflections took 107 ms to scan 56 urls, producing 21868 keys and 23193 values 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fff6449caa8, pid=44057, tid=0x0000000000009903
#
# JRE version: Java(TM) SE Runtime Environment (8.0_162-b12) (build 1.8.0_162-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.162-b12 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libc++abi.dylib+0x10aa8]  __cxxabiv1::__si_class_type_info::has_unambiguous_public_base(__cxxabiv1::__dynamic_cast_info*, void*, int) const+0x4
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/adoeraene/IdeaProjects/DensityGenerator/hs_err_pid44057.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
/usr/local/Cellar/sbt/1.2.6/libexec/bin/sbt-launch-lib.bash: line 59: 44057 Abort trap: 6           "$@"
```

Do you have an idea of what would be causing that? I'm on a macOS Catalina 10.15.5.

**Comment by koen-dejonghe** [comment]
I had the same problem on Mac OSX. Upgrading my JVM fixed it I think. 
I'm now using openjdk version "1.8.0_252".

**Comment by sherpal** [comment]
Indeed, it solved the issue! Thanks.

However a weird phenomenom appeared.
If I do `sbt run`, it works fine. If i do
```
sbt
run
run
```
the first run works fine, but the second one fails with this exception:
```
1:34:42.527 [run-main-1] INFO org.reflections.Reflections - Reflections took 67 ms to scan 55 urls, producing 15783 keys and 16942 values 
[error] (run-main-1) java.lang.ExceptionInInitializerError
[error] java.lang.ExceptionInInitializerError
[error]         at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:53)
[error]         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error]         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error]         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error]         at java.lang.Class.newInstance(Class.java:442)
[error]         at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6185)
[error]         at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
[error]         at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
[error]         at botkop.numsca.Tensor$.apply(Tensor.scala:220)
[error]         at botkop.numsca.Tensor$.apply(Tensor.scala:229)
[error]         at com.b12.Main$.main(Main.scala:13)
[error]         at com.b12.Main.main(Main.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
[error]         at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:51)
[error]         at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:19)
[error]         at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:53)
[error]         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error]         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error]         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error]         at java.lang.Class.newInstance(Class.java:442)
[error]         at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6185)
[error]         at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
[error]         at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
[error]         at botkop.numsca.Tensor$.apply(Tensor.scala:220)
[error]         at botkop.numsca.Tensor$.apply(Tensor.scala:229)
[error]         at com.b12.Main$.main(Main.scala:13)
[error]         at com.b12.Main.main(Main.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcpu in java.library.path
[error]         at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
[error]         at java.lang.Runtime.loadLibrary0(Runtime.java:870)
[error]         at java.lang.System.loadLibrary(System.java:1124)
[error]         at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
[error]         at org.bytedeco.javacpp.Loader.load(Loader.java:777)
[error]         at org.bytedeco.javacpp.Loader.load(Loader.java:684)
[error]         at org.nd4j.nativeblas.Nd4jCpu.<clinit>(Nd4jCpu.java:10)
[error]         at java.lang.Class.forName0(Native Method)
[error]         at java.lang.Class.forName(Class.java:348)
[error]         at org.bytedeco.javacpp.Loader.load(Loader.java:739)
[error]         at org.bytedeco.javacpp.Loader.load(Loader.java:684)
[error]         at org.nd4j.nativeblas.Nd4jCpu$NativeOps.<clinit>(Nd4jCpu.java:63)
[error]         at java.lang.Class.forName0(Native Method)
[error]         at java.lang.Class.forName(Class.java:264)
[error]         at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:29)
[error]         at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:19)
[error]         at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:53)
[error]         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error]         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error]         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error]         at java.lang.Class.newInstance(Class.java:442)
[error]         at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6185)
[error]         at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
[error]         at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
[error]         at botkop.numsca.Tensor$.apply(Tensor.scala:220)
[error]         at botkop.numsca.Tensor$.apply(Tensor.scala:229)
[error]         at com.b12.Main$.main(Main.scala:13)
[error]         at com.b12.Main.main(Main.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] Caused by: java.lang.UnsatisfiedLinkError: Native Library /Users/adoeraene/.javacpp/cache/nd4j-native-0.9.1-macosx-x86_64.jar/org/nd4j/nativeblas/macosx-x86_64/libjnind4jcpu.dylib already loaded in another classloader
[error]         at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1900)
[error]         at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
[error]         at java.lang.Runtime.load0(Runtime.java:809)
[error]         at java.lang.System.load(System.java:1088)
[error]         at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:956)
[error]         at org.bytedeco.javacpp.Loader.load(Loader.java:777)
[error]         at org.bytedeco.javacpp.Loader.load(Loader.java:684)
[error]         at org.nd4j.nativeblas.Nd4jCpu.<clinit>(Nd4jCpu.java:10)
[error]         at java.lang.Class.forName0(Native Method)
[error]         at java.lang.Class.forName(Class.java:348)
[error]         at org.bytedeco.javacpp.Loader.load(Loader.java:739)
[error]         at org.bytedeco.javacpp.Loader.load(Loader.java:684)
[error]         at org.nd4j.nativeblas.Nd4jCpu$NativeOps.<clinit>(Nd4jCpu.java:63)
[error]         at java.lang.Class.forName0(Native Method)
[error]         at java.lang.Class.forName(Class.java:264)
[error]         at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:29)
[error]         at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:19)
[error]         at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:53)
[error]         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error]         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error]         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error]         at java.lang.Class.newInstance(Class.java:442)
[error]         at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6185)
[error]         at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
[error]         at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
[error]         at botkop.numsca.Tensor$.apply(Tensor.scala:220)
[error]         at botkop.numsca.Tensor$.apply(Tensor.scala:229)
[error]         at com.b12.Main$.main(Main.scala:13)
[error]         at com.b12.Main.main(Main.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
```

Have you had something similar or should I dig into nd4j library?

**Comment by koen-dejonghe** [comment]
I'm having the same error when running tests twice:
```
sbt
test
test
```
I believe this is a bug in nd4j. You can work around it by adding 
```
fork := true
```
to build.sbt.
I'm adding this to the code base as well, and it wil be part of a next release.
Thank you for reporting.

**Comment by sherpal** [comment]
Indeed, that did the trick!
Thanks again. I'm closing the issue :)

**Comment by koen-dejonghe** [comment]
Ok. thanks. If you have the time, I would appreciate your comments on a notebook that I've added to the repo:
https://github.com/botkop/numsca/blob/master/notebooks/dl-from-scratch.ipynb
